fix: better easy full-page diff view access
epicweb-dev/kcdshop pull request #132
Opened 2023-07-30 06:10 UTC by onemen

@kentcdodds , your previous approach can trigger 'Save As' dialog in some browsers / operating system, when clicking a link when Alt is down.

this PR improve the use of Alt to navigate to full-page diff view.
follow-up to 9bc0245a6d8785474b80c5b8afdb34796d0a2123

with the code in this PR we only check if Alt is down when the link clicked, only if the Alt is down we navigate to `full-page diff`

2023-07-30 14:05 UTC, kentcdodds requested changes
Thanks. I always hold down the meta key as well and that works for me. This feature is really just for the one making the material anyway.

How would I open in a new tab with the approach you've made? I think we can combine our approaches.

2023-07-30 14:40 UTC, onemen commented
```js
if (event.altKey && (event.ctrlKey || event.metaKey)) {
  event.preventDefault();
  window.open(altDiffUrl, '_blank');
} else if (event.altKey) {
  event.preventDefault();
  navigate(altDiffUrl);
}
```

you can also use `onClickCapture` instead of `onClick` and in the handler function do 
```js
  event.preventDefault();
  navigate(altDiffUrl);
```
when only Alt is down, and `event.currentTarget.href = altDiffUrl` if other modifiers are down.
in this case you also need to add some code to restore the href to its default when no modifier is down.
this approach will use default browser handler for link for all case except for alt. this will prevent triggering 'Save As' 

with this approach there is no extra renders every time you touch your Alt key

2023-07-30 14:47 UTC, kentcdodds commented
That sounds more complicated and I'm not worried about extra renders

2023-07-30 15:09 UTC, onemen commented
Ok

so we can leave the code as is now, and i have to remember to click Alt+Shift to open diff in new tab

2023-07-30 16:01 UTC, kentcdodds commented
I think we can still prevent default and navigate if the user isn't holding down the meta or shift keys

2023-07-31 15:00 UTC, kentcdodds approved these changes
Thanks! I want to keep the listener so the URL is correct while holding down the alt key. This is better for screen readers and other assistive technologies. I'm not at all worried about re-renders when hitting alt. Renders are plenty fast.

Also, the useCallback was unnecessary, and `onClick` works fine.

Thanks!

2023-07-31 15:00 UTC, merged